spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.130.131:3306/leyou
    username: root
    password: root123456


server:
  port: 8080

logging:
  level:  #控制日志级别 要 map类型
     cn.fu.mapper: debug
  #  org.springframework: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true   #驼峰命名法
  type-aliases-package: cn.fu.pojo  #别名扫描包
#  mapper-locations: mapper/*.xml  指定mapper的路径
